Update ob_pl_package_manager.cpp (#1916)
Add (char *) in line 175 due to following error on ppc64le:
  src/pl/ob_pl_package_manager.cpp:175:19: error: cannot initialize a variable of type 'char *' with an rvalue of type 'const char *'
            char *last_slash = strrchr(package_full_path, '/');