Fix dynamic class memaccess compilation error
This has already been landed in 'develop' branch:
https://github.com/oceanbase/oceanbase/commit/edc410ce3c30b8f4a29aa97d836d39b3a64027b9
So we might want to land that commit here instead

Resolve the error (warning treated as error as of -Werror flag):
error: destination for this 'memset' call is a pointer
to dynamic class 'ObParamInfo'; vtable pointer will be
overwritten

Signed-off-by: Hollow Man <hollowman@opensuse.org>